apiVersion: v1
kind: Secret
metadata:
  name: vulremsecrets
type: Opaque
stringData:
    SMARTCHECK_USERNAME: "administrator"
    SMARTCHECK_PASSWORD: "Zxcv7890!"
    #DEEPSECURITY_API_KEY: "078485CC-C7F9-F3F8-7024-1B803F9525D1:lY0Fo0lbGR1jnHQ74ZKNPmes3kXemgj6iXG1QWeI2WQ="
    DEEPSECURITY_API_KEY: "628B90DF-A659-EC58-EEDC-DA63F1ECDE49:DgWJGGpTeVhNm232r69ojDbgrbePExb56zFeHh58ncs="